name: Build Dashboard Tests

on:
  workflow_dispatch:
    inputs:
      pass:
        description: 'Whether this workflow should pass or fail'
        required: true
        type: choice
        default: pass
        options:
          - pass
          - fail

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Print the 'pass' input
      run: echo "pass or fail? ${{ inputs.pass }}"
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: us-east-2
        role-to-assume: arn:aws:iam::108929348570:role/builder-dashboard-aws-playground-github-actions
        role-session-name: BuildDashboardGitHubActions
    - name: AWS list regions
      run: aws account list-regions
