name: Build Dashboard Tests

on:
  workflow_dispatch:
    inputs:
      pass:
        description: 'Whether this workflow should pass or fail'
        required: true
        type: choice
        default: pass
        options:
          - pass
          - fail

jobs:
  test:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Check 'pass' input
      if: inputs.pass == 'fail'
      run: exit 1
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: us-east-2
        role-to-assume: arn:aws:iam::108929348570:role/builder-dashboard-aws-playground-github-actions
        role-session-name: BuildDashboardGitHubActions
    - name: Send failure status
      if: failure()
      working-directory: queue
      run: |
        npm ci
        node sendMessage fail
    - name: Send success status
      if: success()
      working-directory: queue
      run: |
        npm ci
        node sendMessage pass
